// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrHGbLOlmMCiLDc4Sx2yWTS7hrp_Zmmyk',
    appId: '1:587098651014:web:46b187ea401b9114589407',
    messagingSenderId: '587098651014',
    projectId: 'absurdtoolbox',
    authDomain: 'absurdtoolbox.firebaseapp.com',
    storageBucket: 'absurdtoolbox.appspot.com',
    measurementId: 'G-2TD42MGXNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOSTdly-SMpt97m4s-fMVa0Z1he8bptx8',
    appId: '1:587098651014:android:1380e85304c8574c589407',
    messagingSenderId: '587098651014',
    projectId: 'absurdtoolbox',
    storageBucket: 'absurdtoolbox.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1xV8dHW1DFEDLrpH1_buyU-eJZmcr_z0',
    appId: '1:587098651014:ios:876c6562acced470589407',
    messagingSenderId: '587098651014',
    projectId: 'absurdtoolbox',
    storageBucket: 'absurdtoolbox.appspot.com',
    iosClientId:
        '587098651014-cq4oajjglu6961klm1nqb6act2lahus7.apps.googleusercontent.com',
    iosBundleId: 'com.sethbase.absurd_toolbox',
  );
}
